name: Create OPG and Push

on:
  push:
    branches:
      - main
    paths:
      - 'content/post/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/ogp/requirements.txt

      - name: Run main.py
        id: latest_data_id
        run: |
          python scripts/ogp/main.py

      - name: Update README.md
        run: |
          git add -N static/img/images/*.png
          if ! git diff --exit-code --quiet static/img/images/*.png
          then
            git config --global user.name dilmnqvovpnmlib
            git config --global user.email dilmnqvovpnmlib@users.noreply.github.com
            git pull
            git add static/img/images/*.png
            git commit -m 'update OGP images'
            git push origin main
          fi
