name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'content/about/**'
      - 'content/post/**'
      - 'content/scraps/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Invoke another workflow of Creating OPG and Push
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Create OPG and Push
      #     token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/ogp/requirements.txt

      - name: Run main.py
        id: latest_data_id
        run: |
          cd scripts/ogp/
          python main.py

      - name: Update README.md
        run: |
          echo hoge
          git status
          git add -N static/img/images/*.png
          if ! git diff --exit-code --quiet static/img/images/*.png
          then
            git config --global user.name dilmnqvovpnmlib
            git config --global user.email dilmnqvovpnmlib@users.noreply.github.com
            git pull
            git add static/img/images/*.png
            git commit -m 'update OGP images'
            git push origin main
          fi

      # ビルドとデプロイ
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: hakiwata.jp
