name: test

on:
  push:
    branches:
      - main
    paths:
      - 'content/about/**'
      - 'content/post/**'
      - 'content/scraps/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          array_text=(`git log --pretty=%H`);index=1;git diff ${array_text[$index]};git diff ${array_text[$index]} --name-only;echo ${array_text[$index]};
