name: Publish and Dispatch to honOS Repository
on:
  push:
    branches:
      - main
    paths:
      - 'content/post/20210901/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dispatch update a blog of 20210830
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: haytok/honOS
          event-type: update-a-blog-of-20210830
